packages:
  - packages/*

catalogs:
  build:
    dotenv: ^16.5.0
    dotenv-cli: ^8.0.0
    esno: ^4.8.0
    tsup: ^8.3.6
    vite: ^6.1.0
  deps:
    zod: ^3.24.2
  devtool:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    '@antfu/nip': ^0.0.0
    '@cloudflare/workers-types': ^4.20250418.0
    '@hono/node-server': ^1.14.1
    '@types/d3': ^7.4.3
    '@types/node': ^22.13.10
    '@types/vscode': ^1.97.0
    '@typescript-eslint/utils': ^8.29.1
    '@vscode/vsce': ^3.2.2
    bumpp: ^10.0.3
    eslint: ^9.20.1
    pnpm: ^10.8.1
    ts-node: ^10.9.2
    typescript: ^5.8.2
    vite-plugin-node: ^5.0.1
    vscode-ext-gen: ^1.0.0
  extension:
    d3: ^7.9.0
    reactive-vscode: ^0.2.10
  server:
    '@hono/zod-openapi': ^0.19.4
    '@prisma/client': ^6.6.0
    '@prisma/extension-accelerate': ^1.3.0
    hono: ^4.7.7
    prisma: ^6.6.0
    tsx: ^4.19.3
    wrangler: ^4.12.0
  test:
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.0.5
  view:
    '@vitejs/plugin-vue': ^5.2.3
    vue: ^3.5.13
  conflicts_build_:
    tsup: ''
  conflicts_build_c:
    tsup: c
  conflicts_build_ca:
    tsup: ca
  conflicts_build_cat:
    tsup: cat
  conflicts_build_cata:
    tsup: cata
  conflicts_build_catal:
    tsup: catal
  conflicts_build_catalo:
    tsup: catalo
  conflicts_build_catalog:
    tsup: catalog
  conflicts_build_16_5_0:
    dotenv: 16.5.0
  conflicts_devtool_24_3_0:
    '@antfu/ni': 24.3.0
  conflicts_devtool_22_15_17:
    '@types/node': 22.15.17
  conflicts_devtool_1_99_1:
    '@types/vscode': 1.99.1
  conflicts_devtool_3_3_2:
    '@vscode/vsce': 3.3.2
  conflicts_devtool_10_1_0:
    bumpp: 10.1.0
  conflicts_build_4_8_0:
    esno: 4.8.0
  conflicts_devtool_10_10_0:
    pnpm: 10.10.0
  conflicts_extension_0_2_16:
    reactive-vscode: 0.2.16
  conflicts_build_8_4_0:
    tsup: 8.4.0
  conflicts_devtool_5_8_3:
    typescript: 5.8.3
  conflicts_devtool_1_0_2:
    vscode-ext-gen: 1.0.2
onlyBuiltDependencies:
  - esbuild
catalog:
  codebeat-ext-webview: workspa
