packages:
  - packages/*

catalogs:
  build:
    dotenv: ^16.5.0
    dotenv-cli: ^8.0.0
    esno: ^4.8.0
    tsup: ^8.3.6
    vite: ^6.1.0
  deps:
    zod: ^3.24.2
  devtool:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    '@antfu/nip': ^0.0.0
    '@cloudflare/workers-types': ^4.20250418.0
    '@hono/node-server': ^1.14.1
    '@types/d3': ^7.4.3
    '@types/node': ^22.13.10
    '@types/vscode': ^1.97.0
    '@typescript-eslint/utils': ^8.29.1
    '@vscode/vsce': ^3.2.2
    bumpp: ^10.0.3
    eslint: ^9.20.1
    pnpm: ^10.8.1
    ts-node: ^10.9.2
    typescript: ^5.8.2
    vite-plugin-node: ^5.0.1
    vscode-ext-gen: ^1.0.0
  extension:
    d3: ^7.9.0
    reactive-vscode: ^0.2.10
  server:
    '@hono/zod-openapi': ^0.19.4
    '@prisma/client': ^6.6.0
    '@prisma/extension-accelerate': ^1.3.0
    hono: ^4.7.7
    prisma: ^6.6.0
    tsx: ^4.19.3
    wrangler: ^4.12.0
  test:
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.0.5
onlyBuiltDependencies:
  - esbuild
