packages:
  - packages/*

catalogs:
  build:
    dotenv: ^16.5.0
    dotenv-cli: ^8.0.0
    esno: ^4.8.0
    tsup: ^8.3.6
    vite: ^6.1.0
  deps:
    zod: ^3.24.2
  devtool:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    '@antfu/nip': ^0.0.0
    '@cloudflare/workers-types': ^4.20250418.0
    '@hono/node-server': ^1.14.1
    '@sveltejs/kit': ^2.21.1
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@types/d3': ^7.4.3
    '@types/node': ^22.13.10
    '@types/vscode': ^1.97.0
    '@typescript-eslint/utils': ^8.29.1
    '@vscode/vsce': ^3.2.2
    bumpp: ^10.0.3
    eslint: ^9.20.1
    pnpm: ^10.8.1
    svelte-check: ^4.2.1
    tinybench: ^4.0.1
    ts-node: ^10.9.2
    typescript: ^5.8.2
    vite-plugin-node: ^5.0.1
    vscode-ext-gen: ^1.0.0
  extension:
    d3: ^7.9.0
    reactive-vscode: ^0.2.10
  server:
    '@hono/trpc-server': ^0.3.4
    '@hono/zod-openapi': ^0.19.4
    '@prisma/client': ^6.6.0
    '@prisma/extension-accelerate': ^1.3.0
    '@trpc/server': ^11.1.3
    hono: ^4.7.7
    prisma: ^6.6.0
    trpc: ^0.11.3
    tsx: ^4.19.3
    wrangler: ^4.12.0
  test:
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.0.5
  view:
    '@vitejs/plugin-vue': ^5.2.3
    vue: ^3.5.13
  web:
    '@melt-ui/pp': ^0.3.2
    '@melt-ui/svelte': ^0.86.6
    '@tailwindcss/nesting': ^0.0.0-insiders.565cd3e
    '@tailwindcss/postcss': ^4.1.7
    '@tailwindcss/vite': ^4.1.7
    '@trpc/client': ^11.1.4
    autoprefixer: ^10.4.21
    clsx: ^2.1.1
    postcss: ^8.5.3
    postcss-import: ^16.1.0
    svelte: ^5.33.1
    svelte-preprocess: ^6.0.3
    tailwind-merge: ^3.3.0
    tailwindcss: ^4.1.7
    vite-plugin-devtools-json: ^0.2.0
onlyBuiltDependencies:
  - esbuild
