packages:
  - packages/*

catalogs:
  devtool:
    '@antfu/eslint-config': ^4.2.1
    '@antfu/ni': ^23.3.1
    '@types/node': ^22.13.4
    '@types/vscode': ^1.97.0
    '@vscode/vsce': ^3.2.2
    'bumpp': ^10.0.3
    'eslint': ^9.20.1
    'pnpm': ^10.8.1
    'typescript': ^5.7.3
    'vscode-ext-gen': ^1.0.0
  plugin:
    'reactive-vscode': ^0.2.10
    'vscode-ext-gen': ^1.0.0
  test:
    'vitest': ^3.0.5
  build:
    'tsup': ^8.3.6
    'vite': ^6.1.0
    'esno': ^4.8.0